"""add thumbnail

Revision ID: 8484ec63af68
Revises: 
Create Date: 2021-12-10 14:08:33.275585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8484ec63af68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'thumbnail')
    # ### end Alembic commands ###
